inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
    - 'config/routes.rb'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Max: 500
  Exclude:
  - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 100
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 8

Style/BlockDelimiters:
  Exclude:
  - 'spec/**/*.rb'

# we can't remove this until we're certain prod has no invalid messages
Rails/SkipsModelValidations:
  Exclude:
    - 'app/controllers/reporting_relationships_controller.rb'
