inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
    - 'config/routes.rb'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Max: 500
  Exclude:
  - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 100
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 8

Style/BlockDelimiters:
  Exclude:
  - 'spec/**/*.rb'

# For puts statements in seeds
Rails/Output:
  Exclude:
    - 'db/seeds.rb'

# Form builder needs html_safe to work
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/gcf_form_builder.rb'

# Rubocop likes documentation in weird ways
Style/Documentation:
  Enabled: false

# We're not planning on a ruby 3 migration any time soon
# more info: https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3
# more info: https://rubocop.readthedocs.io/en/latest/cops_style/#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: false
